# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
          id: fos_user.user_provider.username

    encoders:
      AppBundle\Security\Webservice\UserWebservice: bcrypt
      FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        secured_area:
          anonymous: ~
          form_login:
            provider: fos_userbundle
            csrf_token_generator: security.csrf.token_manager
          logout:
            path: fos_user_security_logout
            target: /login
          oauth:
              resource_owners:
                  facebook:           "/login/check-facebook"
                  google:             "/login/check-google"
              login_path:        /login
              use_forward:       false
              failure_path:      /login
              oauth_user_provider:
                  service: my.oauth_aware.user_provider.service

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        localnetwork:
                pattern:  ^/localnetwork
                anonymous: ~

        main:
            pattern: ^/
            form_login:
              provider: fos_userbundle
              csrf_token_generator: security.csrf.token_manager
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
      - {path: ^/localnetwork, roles: ROLE_USER_IP, ip: 192.168.178.20 }
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin/, role: ROLE_ADMIN }
      - { path: ^/lessons/new, role: ROLE_ADMIN}
