AppBundle\Entity\User:
 properties:
    # Your custom fields in your user entity, here is an example with FirstName
        firstName:
            - NotBlank:
                message: _user.first_name.blank
                groups: [ "Profile" ]
            - Length:
                min: 2
                minMessage: _user.first_name.short
                max: 255
                maxMessage: _user.first_name.long
                groups: [ "Profile" ]

FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
             fields: email
             errorPath: email
             message: fos_user.email.already_used
             groups: [ "Registration", "Profile" ]

    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "Registration", "Profile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "Registration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "Registration", "Profile" ]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "Registration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                max: 4096
                minMessage: fos_user.password.short
                groups: [ "Registration", "Profile", "ResetPassword", "ChangePassword"]

FOS\UserBundle\Model\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "Registration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "Registration" ]

FOS\UserBundle\Propel\User:
    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "Registration", "Profile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "Registration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "Registration", "Profile" ]

        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "Registration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                max: 4096
                minMessage: fos_user.password.short
                groups: [ "Registration", "Profile", "ResetPassword", "ChangePassword"]


FOS\UserBundle\Propel\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "Registration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "Registration" ]